apiVersion: v1
kind: Service
metadata:
  name: anchor-service
  labels:
    name: anchor-service

spec:
  selector:
    app: anchorapi

  ports:
    - port: 3000
      targetPort: 3000

  type: LoadBalancer
