apiVersion: v1

kind: Pod

metadata:
  name: anchorapi
  labels:
    app: anchorapi

spec:
  containers:
    - name: anchorapi-container
      image: mabdockerid/ledger-anchorapi:latest
      ports:
          - containerPort: 3000
      imagePullPolicy: Always
      volumeMounts:
          - mountPath: usr/src/app/config
            name: cache-volume
  initContainers:
    - name: ledger-emptydir
      image: mabdockerid/ledger-emptydir:latest
      env:
        - name: GitCloneURL
          value: https://github.com/bmastahac/HyperledgerFabric.git
        - name: PATHToGitClone
          value: usr/src/app/config
      volumeMounts:
          - mountPath: usr/src/app/config
            name: cache-volume
  volumes:
   - name: cache-volume
     emptyDir: {}