apiVersion: v1

kind: PersistentVolume

metadata:
  name: fabric-pv
  labels:
    type: local
    name: fabricfiles

spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /nfs/fabric
    server: nfs
    readOnly: false