--- #---------------- Orderer0 Deployment ---------------
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: orderer0
  name: orderer0
  namespace: hyperledger
spec:
  selector:
    matchLabels:
      app: orderer0
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: orderer0
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              podAffinityTerm:
                topologyKey: "kubernetes.io/hostname"
      containers:
        - args:
            - orderer
          env:
            - name: FABRIC_LOGGING_SPEC
              value: DEBUG
            - name: ORDERER_OPERATIONS_LISTENADDRESS
              value: 0.0.0.0:8443
            - name: ORDERER_METRICS_PROVIDER
              value: prometheus
            - name: ORDERER_GENERAL_GENESISFILE
              value: /usr/src/crypto-config/channel-artifacts/genesis.block
            - name: ORDERER_GENERAL_GENESISMETHOD
              value: file
            - name: ORDERER_GENERAL_LISTENADDRESS
              value: 0.0.0.0
            - name: ORDERER_GENERAL_LOCALMSPDIR
              value: /usr/src/crypto-config/crypto-config/ordererOrganizations/consortium/orderers/orderer0/msp
            - name: ORDERER_GENERAL_LOCALMSPID
              value: OrdererMSP
            - name: ORDERER_GENERAL_TLS_CERTIFICATE
              value: /usr/src/crypto-config/crypto-config/ordererOrganizations/consortium/orderers/orderer0/tls/server.crt
            - name: ORDERER_GENERAL_TLS_ENABLED
              value: "true"
            - name: ORDERER_GENERAL_TLS_PRIVATEKEY
              value: /usr/src/crypto-config/crypto-config/ordererOrganizations/consortium/orderers/orderer0/tls/server.key
            - name: ORDERER_GENERAL_TLS_ROOTCAS
              value: "[/usr/src/crypto-config/crypto-config/ordererOrganizations/consortium/orderers/orderer0/tls/ca.crt]"
            - name: ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE
              value: /usr/src/crypto-config/crypto-config/ordererOrganizations/consortium/orderers/orderer0/tls/server.crt
            - name: ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY
              value: /usr/src/crypto-config/crypto-config/ordererOrganizations/consortium/orderers/orderer0/tls/server.key
            - name: ORDERER_GENERAL_CLUSTER_ROOTCAS
              value: "[/usr/src/crypto-config/crypto-config/ordererOrganizations/consortium/orderers/orderer0/tls/ca.crt]"
          image: hyperledger/fabric-orderer:amd64-2.0.1
          name: orderer
          ports:
            - containerPort: 7050
            - containerPort: 8443
          volumeMounts:
            - mountPath: var/hyperledger/production
              name: storagevolume
            - mountPath: usr/src/crypto-config
              name: cryptovolume
          workingDir: /opt/gopath/src/github.com/hyperledger/fabric

      restartPolicy: Always

      initContainers:
        - name: ledger-emptydir
          image: mabdockerid/ledger-emptydir:latest
          env:
           - name: GitCloneURL
             value: https://github.com/bmastahac/HyperledgerFabric.git
           - name: PATHToGitClone
             value: usr/src/crypto-config
          volumeMounts:
            - mountPath: usr/src/crypto-config
              name: cryptovolume

      volumes:
        - name: cryptovolume
          emptyDir: {}
        - name: storagevolume
          emptyDir: {}

