---
apiVersion: batch/v1
kind: Job
metadata:
  name: utils
spec:
  backoffLimit: 1
  template:
    metadata:
      name: utils
    spec:
      restartPolicy: "Never"
      volumes:
        - name: sharedvolume
          persistentVolumeClaim:
            claimName: shared-pvc

      containers:
        - name: cryptogen
          image: hyperledger/fabric-tools:amd64-2.1.0
          imagePullPolicy: Always
          command:
           - sh
           - -c
           - |
             cd /shared
             rm -rf /shared/*
             wget https://github.com/PharmaLedger-IMI/hyperledger-anchoring-demo/raw/master/Kubernetes/helm/crypto/network.tar.gz
             tar -xf network.tar.gz
             ls

          volumeMounts:
            - mountPath: /shared
              name: sharedvolume
