apiVersion: v1

kind: Pod

metadata:
  name: cache-pod
  labels:
    name: cache-pod

spec:
  containers:
    - name: ledger-emptydir-container
      image: mabdockerid/ledger-emptydir:latest

      env:
        - name: GitCloneURL
          value: https://github.com/bmastahac/HyperledgerFabric.git
        - name: PATHToGitClone
          value: /data/
      volumeMounts:
        - mountPath: /config
          name: cache-volume
  volumes:

    - name: cache-volume
      emptyDir: {}

